apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-resize
  namespace: apps
  labels:
    app: demo-resize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-resize
  template:
    metadata:
      labels:
        app: demo-resize
    spec:
      containers:
        - name: demo-resize
          image: demo-resize:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-opentelemetry-collector.observability.svc.cluster.local:4317"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "90Mi"
              cpu: "200m"
          resizePolicy:
          - resourceName: cpu
            restartPolicy: RestartContainer
          - resourceName: memory
            restartPolicy: NotRequired
---
apiVersion: v1
kind: Service
metadata:
  name: demo-resize
  namespace: apps
spec:
  selector:
    app: demo-resize
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: NodePort