apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-pentest-pod
  namespace: apps
  labels:
    app: k8s-pentest-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-pentest-pod
  template:
    metadata:
      labels:
        app: k8s-pentest-pod
    spec:
      serviceAccountName: pod-destroyer
      containers:
        - name: k8s-pentest-pod
          image: bustakube/alpine-peirates:v1.1.27d
          imagePullPolicy: IfNotPresent
---